/vis/open
/vis/drawVolume
/vis/viewer/set/autoRefresh true
/vis/scene/add/trajectories smooth
/vis/scene/add/scale 10 cm
/vis/scene/add/axes 0 0 0 10 cm
/vis/viewer/set/viewpointVector 0.5 0.5 1
/vis/scene/add/eventID
/vis/scene/endOfEventAction accumulate
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton cyan
# /vis/viewer/set/background 0.82 0.86 0.93
/vis/viewer/refresh
/tracking/verbose 0
